### ISSUE TITLE
No birthday found

### ISSUE THREAD

**Issue by valentin8709** [skjnldsv/Owncloud-FBSync#7]
Hi again,
Sorry but I have another bug =/

I installed the last version (1.5), and remove all birthday with your new feature. Then I sync birthdays and have 100% errors: "No birthday found" for each contact. I checked on Facebook and people have registered their birthday.

Any idea where this bug come from?

**Comment by skjnldsv** [comment]
No problem! :)
Okay, so this is definitely coming from facebok this time! 
I can definitely  see this with you, but I will need very specific details. Because i'm parsing the facebook page output to get info, I will need the source code returned by one of the request made by my app on your system! 

Install this version: https://1fichier.com/?wtdk42x3s0
Go into fbsync/templates/debug.php
In the line 9, replace xxxxxx by a facebook id that match a friend of yours. (http://findmyfbid.com/)
Save the file and go into https://yourowncloudurl/index.php/apps/fbsync/debug

It will output the exact data that facebook send back.
Find the birthday date, right click > inspect
Then make a screenshot of the html data wich lead to the birthday info.
Make sure no private data appear on the screenshot for privacy issues. ;)

Edit: i'm using chrome, if you're using firefox, it should be almost the exact same way :)
![capture d ecran_2015-11-28_19-15-05](https://cloud.githubusercontent.com/assets/14975046/11453264/5be73970-9604-11e5-9dc4-030ac45dc297.png)

**Comment by skjnldsv** [comment]
@valentin8709 Any news? :p

**Comment by valentin8709** [comment]
Sorry I can't check that for now, I'll test tomorrow =)

**Comment by valentin8709** [comment]
Okay that's what I got:
![screenshot from 2015-11-30 19 30 03](https://cloud.githubusercontent.com/assets/6785619/11480650/d7b72c46-9798-11e5-9336-60ce70707b12.png)

Indeed it's different from you, can you tell me what to change in the php file (and which file)?

**Comment by skjnldsv** [comment]
Perfect! ;)
Thats what I wanted!
Fix coming next update!

Thank you very much.

**Comment by valentin8709** [comment]
Thank you =D

**Comment by skjnldsv** [comment]
Well, this is going to be more difficult than planned! :/
Convert foreign languages dates is going to be a lot more hader than it was.

**Comment by skjnldsv** [comment]
Trying to avoid using the api is hard! :(

**Comment by valentin8709** [comment]
Oh =/ Can I help? If you tell me what you have in input, and what you want in output, I can perhaps do that for you in php. Not sure but I can try...

**Comment by skjnldsv** [comment]
Well, because I don't want to use the facebook api, I'm parsing the data outputted by facebook.
When using facebook ids or the name of your contacts, there's no languages issues.

But facebook outputs its birthdays with the defined language in your facebook feed.
I'm using the strtotime function for php, which try to convert a string into a date. But this function require an English date. So, either i find another way to get the birthdays or I find something else to convert or detect languages, or no birthdays for non English natives! :/

**Comment by valentin8709** [comment]
Oh so I just have to switch my Facebook in english? I'm trying that right now =)

**Comment by skjnldsv** [comment]
Yes, it should works.
But its a very inconvenient way to do so. :)

**Comment by valentin8709** [comment]
No problem for that =) It works great now, thank you very much!

**Comment by skjnldsv** [comment]
Well, maybe it's good for you. To be fair, I wouldn't mind changing my language to sync birthdays.
But if my goal is to provide the best app possible, I shouldn't be allowing myself to do so. 

Maybe should I just put a warning saying you need to put English as default language just for the sync. Or automatically switch it and switch it backs to the original language. :/

**Comment by valentin8709** [comment]
Couldn't you do that in your program? I mean your app switching Facebook langage? As a result the user wouldn't see nothing =)

**Comment by skjnldsv** [comment]
Yes, I guess i could. Not the best way to do that; but after all, you don't need to sync the birthdays everyday!

**Comment by skjnldsv** [comment]
I finally decided to but a warning explaining you need to put your facebook in English for the bday sync to work.
I don't want to bother implementing some kind of dirty coding to change language or so. :)
